#!/usr/bin/env python
'''
    Copyright (c) 2016 Tim Savannah All Rights Reserved.
    This software is licensed under the terms of the GPLv3.
    This may change at my discretion, retroactively, and without notice.

    You should have received a copy of this with the source distribution as a file titled, LICENSE.

    The most current license can be found at:
    https://github.com/kata198/usrsvc/LICENSE

    This location may need to be changed at some point in the future, in which case
    you are may email Tim Savannah <kata198 at gmail dot com>, or find them on the
    current website intended for distribution of usrsvc.

    usrsvc is the tool to start/stop/restart and get status on services. usrsvcd is the daemon for autostart, autorestart, monitoring, etc.
'''
# vim:set ts=4 shiftwidth=4 softtabstop=4 expandtab :

import sys
from usrsvcmod.client.usrsvc import Usrsvc
from usrsvcmod.constants import ReturnCodes
from usrsvcmod.debug import toggleDebug

if __name__ == '__main__':
    if '--version' in sys.argv:
        from usrsvcmod import __version__ as vers
        sys.stderr.write("usrsvc version %s\n" %(vers,))
        sys.exit(ReturnCodes.HELP_MESSAGE)

    if '--debug' in sys.argv:
        sys.stderr.write('DEBUG ON\n')
        toggleDebug(True)
        sys.argv.remove('--debug')

    try:
        client = Usrsvc()
    except ValueError:
        sys.exit(ReturnCodes.INVALID_CONFIG)

    sys.exit(client.main(sys.argv))

# vim:set ts=4 shiftwidth=4 softtabstop=4 expandtab :
